import fs from 'node:fs/promises';
import path from 'node:path';

/**
 * The resident fragment: one rule, delivered as a file the agent always reads,
 * rather than as a skill that loads when a trigger matches.
 *
 * It is an ordinary file at a reserved directory inside the target directory
 * this tool already governs, so it inherits `contained`, the tree checks, the
 * `pending` journal, retirement, drift refusal, `--force` and exact uninstall
 * from `installSkills` with no new machinery and no new record type. ADR-0022
 * records the decision and the alternative it refused.
 *
 * This tool never edits an instruction file. It prints the import line, and a
 * `doctor` finding detects whether the line took.
 */

/** The directory name the fragment installs under, inside the target tree. */
export const RESIDENT_NAME = 'stylewright-resident';

/**
 * The tier recorded in the manifest. It is not one of `TIERS`, on purpose: a
 * tier selection names skills, and `uninstall --tier craft` must not reach the
 * fragment. `--all` and `--skill` both still do.
 */
export const RESIDENT_TIER = 'resident';

/** The one file the pilot ships. ADR-0022 rules out a second one. */
export const RESIDENT_FILE = 'navigable-references.md';

/** Where the generated fragment lives in this repository. */
export const RESIDENT_SOURCE = 'resident';

/** The skill the fragment is generated from, and the alternate delivery. */
export const RESIDENT_SKILL = 'navigable-references';

/**
 * The platforms the fragment installs to.
 *
 * `@path` is a Claude Code feature. Issue #24 asks whether Codex has an
 * equivalent and this repository has not answered it, so the fragment is
 * refused there rather than installed as a file no instruction file can reach.
 * An import line that silently fails is worse than no resident layer, because
 * the user then believes a rule is active when it is not.
 *
 * `agents` is a cross-agent directory convention rather than an agent, so it
 * has no instruction file of its own and is refused for the same reason.
 */
export const RESIDENT_PLATFORMS = ['claude', 'cowork'];

/**
 * What `doctor` looks for in an instruction file.
 *
 * A substring and not a Markdown model. The import line's own spelling varies
 * with where the user keeps their instruction file, and every spelling of it
 * ends in this. A false negative costs a warning, which is the trade this
 * design makes on purpose.
 */
export const RESIDENT_MARK = `${RESIDENT_NAME}/${RESIDENT_FILE}`;

export const RESIDENT_DESCRIPTION =
  'The navigable-references rule, as a file your instruction file imports. '
  + 'Always in context, with no trigger to miss.';

/**
 * The sections of `SKILL.md` the fragment carries, in this order.
 *
 * Both are graded in `grounding/craft/navigable-references.md`, as rows E-02
 * through E-11. The fragment therefore carries no rule that the matrix does
 * not already dispose of, which is what keeps a generated copy from becoming
 * an ungraded second skill.
 */
export const RESIDENT_SECTIONS = [
  'Give the reference a form the reader can follow',
  'Find the line at the moment you cite it',
];

const HEADER = '<!-- Generated by `npm run check:resident -- --write` from '
  + 'skills/craft/navigable-references/SKILL.md. Do not edit this file. -->';

export class ResidentDrift extends Error {
  constructor(message) {
    super(message);
    this.name = 'ResidentDrift';
  }
}

/**
 * The body of a Markdown document, with the front matter removed and the line
 * ending normalised. `readFrontmatter` in `catalog.js` states why the second
 * half matters.
 */
function body(text) {
  return text.replace(/\r\n/g, '\n').replace(/^---\n[\s\S]*?\n---\n/, '');
}

/**
 * One `##` section of a document, heading included, from the heading line to
 * the line before the next heading of any level.
 *
 * It throws on a heading it cannot find rather than returning nothing. A
 * renamed section would otherwise shrink the fragment silently, and a rule
 * that quietly stopped shipping is the failure this whole decision exists to
 * prevent.
 */
function section(text, heading) {
  const lines = body(text).split('\n');
  const start = lines.findIndex((line) => line === `## ${heading}`);
  if (start === -1) {
    throw new ResidentDrift(
      `skills/craft/${RESIDENT_SKILL}/SKILL.md has no section "## ${heading}". `
      + 'The fragment is generated from that section, so renaming it here means '
      + 'naming it in RESIDENT_SECTIONS too.');
  }
  let end = start + 1;
  while (end < lines.length && !/^#{1,6} /.test(lines[end])) end++;
  return lines.slice(start, end).join('\n').replace(/\n+$/, '');
}

/** The document's first heading, which names the rule the fragment carries. */
function title(text) {
  const line = body(text).split('\n').find((l) => l.startsWith('# '));
  if (!line) {
    throw new ResidentDrift(
      `skills/craft/${RESIDENT_SKILL}/SKILL.md has no top-level heading.`);
  }
  return line;
}

/**
 * The fragment, derived from the skill.
 *
 * Every line but the header comment is copied verbatim out of `SKILL.md`, so
 * the fragment asserts nothing the grounding matrix has not already disposed
 * of. The header is a comment rather than prose for the same reason: it states
 * where the file came from and instructs nobody.
 */
export function renderResident(skillText) {
  const parts = RESIDENT_SECTIONS.map((h) => section(skillText, h));
  return `${HEADER}\n\n${title(skillText)}\n\n${parts.join('\n\n')}\n`;
}

async function readOrNull(abs) {
  try {
    return await fs.readFile(abs, 'utf8');
  } catch (err) {
    if (err.code === 'ENOENT') return null;
    throw err;
  }
}

export function skillPath(repoRoot) {
  return path.join(repoRoot, 'skills', 'craft', RESIDENT_SKILL, 'SKILL.md');
}

export function residentPath(repoRoot) {
  return path.join(repoRoot, RESIDENT_SOURCE, RESIDENT_FILE);
}

/**
 * Does the shipped fragment still match the skill it is generated from?
 *
 * Returns `{ expected, actual, problems }`. It reads and compares, and it
 * never writes, so the same function serves the check and the generator.
 * `scripts/check-resident.mjs` owns the exit code and the writing.
 */
export async function checkResident(repoRoot) {
  const skillText = await readOrNull(skillPath(repoRoot));
  if (skillText === null) {
    return {
      expected: null,
      actual: null,
      problems: [`${skillPath(repoRoot)} is missing, and the fragment is generated from it.`],
    };
  }
  const expected = renderResident(skillText);
  const actual = await readOrNull(residentPath(repoRoot));
  if (actual === null) {
    return {
      expected,
      actual,
      problems: [`${RESIDENT_SOURCE}/${RESIDENT_FILE} is missing. Run \`npm run check:resident -- --write\`.`],
    };
  }
  if (actual.replace(/\r\n/g, '\n') !== expected) {
    return {
      expected,
      actual,
      problems: [
        `${RESIDENT_SOURCE}/${RESIDENT_FILE} no longer matches `
        + `skills/craft/${RESIDENT_SKILL}/SKILL.md. One rule has two forms, and they `
        + 'have drifted. Run `npm run check:resident -- --write`.',
      ],
    };
  }
  return { expected, actual, problems: [] };
}

/**
 * The fragment as an install source, shaped exactly like a catalog entry so
 * that `installSkills` copies it through the code path every skill takes.
 *
 * An empty list when the directory is absent, which is what a checkout missing
 * the generated file looks like. The check above is what fails that state, and
 * failing it twice would report one problem as two.
 */
export async function loadResidents(repoRoot) {
  const dir = path.join(repoRoot, RESIDENT_SOURCE);
  if (await readOrNull(path.join(dir, RESIDENT_FILE)) === null) return [];
  return [{
    name: RESIDENT_NAME,
    tier: RESIDENT_TIER,
    dir,
    description: RESIDENT_DESCRIPTION,
  }];
}

/**
 * The line the user pastes, spelled relative to the instruction file that will
 * hold it.
 *
 * Relative and not absolute, because a dotfiles repository travels between
 * machines and a home directory is not the same path on two of them. Spelled
 * with `/` on every platform, because that is what an import line takes.
 */
export function importLine({ targetDir, instructionFile }) {
  const abs = path.join(targetDir, RESIDENT_NAME, RESIDENT_FILE);
  const rel = path.relative(path.dirname(instructionFile), abs);
  return `@${rel.split(path.sep).join('/')}`;
}
