import fs from 'node:fs/promises';
import path from 'node:path';
import { destinationState, ensureDir, removeAt } from './tree.js';
import { stagingPath } from './journal.js';

/**
 * The resident fragment: one rule, delivered as a file the agent always reads,
 * rather than as a skill that loads when a trigger matches.
 *
 * It is an ordinary file at a reserved directory inside the target directory
 * this tool already governs, so it inherits `contained`, the tree checks, the
 * `pending` journal, retirement, drift refusal, `--force` and exact uninstall
 * from `installSkills` with no new machinery and no new record type. ADR-0022
 * records the decision and the alternative it refused.
 *
 * This tool never edits an instruction file. It prints the import line, and a
 * `doctor` finding detects whether the line took.
 */

/** The directory name the fragment installs under, inside the target tree. */
export const RESIDENT_NAME = 'stylewright-resident';

/**
 * The tier recorded in the manifest. It is not one of `TIERS`, on purpose: a
 * tier selection names skills, and `uninstall --tier craft` must not reach the
 * fragment. `--all` and `--skill` both still do.
 */
export const RESIDENT_TIER = 'resident';

/** The one file the pilot ships. ADR-0022 rules out a second one. */
export const RESIDENT_FILE = 'navigable-references.md';

/** Where the generated fragment lives in this repository. */
export const RESIDENT_SOURCE = 'resident';

/** The skill the fragment is generated from, and the alternate delivery. */
export const RESIDENT_SKILL = 'navigable-references';

/**
 * The platforms the fragment installs to.
 *
 * `@path` is a Claude Code feature. Issue #24 asks whether Codex has an
 * equivalent and this repository has not answered it, so the fragment is
 * refused there rather than installed as a file no instruction file can reach.
 * An import line that silently fails is worse than no resident layer, because
 * the user then believes a rule is active when it is not.
 *
 * `agents` is a cross-agent directory convention rather than an agent, so it
 * has no instruction file of its own and is refused for the same reason.
 */
export const RESIDENT_PLATFORMS = ['claude', 'cowork'];

export const RESIDENT_DESCRIPTION =
  'The navigable-references rule, as a file your instruction file imports. '
  + 'Always in context, with no trigger to miss. Install it by name, because '
  + 'no tier selects it.';

/**
 * The sections of `SKILL.md` the fragment carries, in this order.
 *
 * Both are graded in `grounding/craft/navigable-references.md`. Those two
 * sections are rows E-02 through E-11, and the document heading the fragment
 * also carries is row N-03. So every writing rule in the fragment is one the
 * matrix already disposes of, and a generated copy does not become an ungraded
 * second skill.
 *
 * The header comment below is the one line no matrix covers. It is provenance
 * addressed to whoever opens the generated file, and it states no writing
 * rule.
 */
export const RESIDENT_SECTIONS = [
  'Give the reference a form the reader can follow',
  'Find the line at the moment you cite it',
];

const HEADER = '<!-- Generated by `npm run check:resident -- --write` from '
  + 'skills/craft/navigable-references/SKILL.md. Do not edit this file. -->';

export class ResidentDrift extends Error {
  constructor(message) {
    super(message);
    this.name = 'ResidentDrift';
  }
}

/**
 * The body of a Markdown document, with the front matter removed and the line
 * ending normalised. `readFrontmatter` in `catalog.js` states why the second
 * half matters.
 */
function body(text) {
  return text.replace(/\r\n/g, '\n').replace(/^---\n[\s\S]*?\n---\n/, '');
}

/**
 * One `##` section of a document, heading included, from the heading line to
 * the line before the next heading of any level.
 *
 * It throws on a heading it cannot find rather than returning nothing. A
 * renamed section would otherwise shrink the fragment silently, and a rule
 * that quietly stopped shipping is the failure this whole decision exists to
 * prevent.
 */
function section(text, heading) {
  const lines = body(text).split('\n');
  const start = lines.findIndex((line) => line === `## ${heading}`);
  if (start === -1) {
    throw new ResidentDrift(
      `skills/craft/${RESIDENT_SKILL}/SKILL.md has no section "## ${heading}". `
      + 'The fragment is generated from that section, so renaming it here means '
      + 'naming it in RESIDENT_SECTIONS too.');
  }
  let end = start + 1;
  while (end < lines.length && !/^#{1,6} /.test(lines[end])) end++;
  return lines.slice(start, end).join('\n').replace(/\n+$/, '');
}

/** The document's first heading, which names the rule the fragment carries. */
function title(text) {
  const line = body(text).split('\n').find((l) => l.startsWith('# '));
  if (!line) {
    throw new ResidentDrift(
      `skills/craft/${RESIDENT_SKILL}/SKILL.md has no top-level heading.`);
  }
  return line;
}

/**
 * The fragment, derived from the skill.
 *
 * Every line but the header comment is copied verbatim out of `SKILL.md`, so
 * every writing rule the fragment carries is one the grounding matrix has
 * already disposed of.
 *
 * The header is a comment rather than prose, and it does carry an instruction:
 * it tells a maintainer of this repository not to edit the generated file. It
 * is deliberately the only line here that is not graded, it is addressed to a
 * maintainer rather than to a writer, and a Markdown reader renders none of
 * it. ADR-0022 states the same boundary.
 */
export function renderResident(skillText) {
  const parts = RESIDENT_SECTIONS.map((h) => section(skillText, h));
  return `${HEADER}\n\n${title(skillText)}\n\n${parts.join('\n\n')}\n`;
}

/**
 * The text at `abs`, or `null` when nothing readable is there.
 *
 * ENOENT and EISDIR both mean "no text here", and only the first was caught.
 * A directory at the fragment path therefore threw an EISDIR stack out of the
 * check, before `writeResident` below could classify the path and refuse it in
 * words. Reading them alike is what lets that refusal be reached.
 */
async function readOrNull(abs) {
  try {
    return await fs.readFile(abs, 'utf8');
  } catch (err) {
    if (err.code === 'ENOENT' || err.code === 'EISDIR') return null;
    throw err;
  }
}

export function skillPath(repoRoot) {
  return path.join(repoRoot, 'skills', 'craft', RESIDENT_SKILL, 'SKILL.md');
}

export function residentPath(repoRoot) {
  return path.join(repoRoot, RESIDENT_SOURCE, RESIDENT_FILE);
}

/**
 * Does the shipped fragment still match the skill it is generated from?
 *
 * Returns `{ expected, actual, problems }`. It reads and compares, and it
 * never writes, so the same function serves the check and the generator.
 * `scripts/check-resident.mjs` owns the exit code and the writing.
 */
export async function checkResident(repoRoot) {
  const skillText = await readOrNull(skillPath(repoRoot));
  if (skillText === null) {
    return {
      expected: null,
      actual: null,
      problems: [`${skillPath(repoRoot)} is missing, and the fragment is generated from it.`],
    };
  }
  const expected = renderResident(skillText);
  const actual = await readOrNull(residentPath(repoRoot));
  if (actual === null) {
    return {
      expected,
      actual,
      problems: [`${RESIDENT_SOURCE}/${RESIDENT_FILE} is missing. Run \`npm run check:resident -- --write\`.`],
    };
  }
  if (actual.replace(/\r\n/g, '\n') !== expected) {
    return {
      expected,
      actual,
      problems: [
        `${RESIDENT_SOURCE}/${RESIDENT_FILE} no longer matches `
        + `skills/craft/${RESIDENT_SKILL}/SKILL.md. One rule has two forms, and they `
        + 'have drifted. Run `npm run check:resident -- --write`.',
      ],
    };
  }
  return { expected, actual, problems: [] };
}

/**
 * Write the generated fragment into this repository.
 *
 * A new write surface inherits the tree checks or it repeats the defect
 * AGENTS.md names, and this one is no exception for being a build step. The
 * destination is classified before anything happens, every directory component
 * goes through `ensureDir`, and the bytes land beside the destination and are
 * renamed over it, so the file is whole or untouched. A link at the
 * destination is refused rather than written through.
 *
 * The staging name comes from `journal.js`, so this surface reserves no name
 * of its own.
 */
export async function writeResident(repoRoot, text) {
  const dest = residentPath(repoRoot);
  await ensureDir(path.dirname(dest), repoRoot);
  const state = await destinationState(dest);
  if (state !== 'absent' && state !== 'file') {
    throw new Error(
      `${RESIDENT_SOURCE}/${RESIDENT_FILE} is a ${state}, not a regular file. `
      + 'Remove it and run again.');
  }
  const staged = stagingPath(dest);
  // The name belongs to this tool: it is the destination plus a suffix nothing
  // else writes. Anything there is a stopped run's own leftover.
  await removeAt(staged);
  // `wx`, so a file this tool creates refuses an existing path rather than
  // truncating it, and does not follow a link.
  await fs.writeFile(staged, text, { flag: 'wx' });
  await fs.rename(staged, dest);
  return dest;
}

/**
 * The fragment as an install source, shaped exactly like a catalog entry so
 * that `installSkills` copies it through the code path every skill takes.
 *
 * An empty list when the directory is absent, which is what a checkout missing
 * the generated file looks like. The check above is what fails that state, and
 * failing it twice would report one problem as two.
 */
export async function loadResidents(repoRoot) {
  const dir = path.join(repoRoot, RESIDENT_SOURCE);
  if (await readOrNull(path.join(dir, RESIDENT_FILE)) === null) return [];
  return [{
    name: RESIDENT_NAME,
    tier: RESIDENT_TIER,
    dir,
    description: RESIDENT_DESCRIPTION,
  }];
}

/**
 * The line the user pastes, spelled relative to the instruction file that will
 * hold it.
 *
 * Relative and not absolute, because a dotfiles repository travels between
 * machines and a home directory is not the same path on two of them. Spelled
 * with `/` on every platform, because that is what an import line takes.
 */
export function importLine({ targetDir, instructionFile }) {
  const abs = path.join(targetDir, RESIDENT_NAME, RESIDENT_FILE);
  const rel = path.relative(path.dirname(instructionFile), abs);
  return `@${rel.split(path.sep).join('/')}`;
}
